name = "Rhea"
uuid = "33b3dd72-4584-4518-9b0b-a4958c4a7919"
version = "1.0.0-DEV"
authors = ["Demetrius Michael <arrrwalktheplank@gmail.com>"]

[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
BufferedStreams = "e1450e63-4bb3-523b-b2a4-4ffa8c0fd77d"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
Mmap = "a63ad114-7e13-5084-954f-fe012c677804"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
ProfileView = "c46f51b8-102a-5cf2-8d2c-8597cb0e0da7"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"

[compat]
BenchmarkTools = "1.6.3"
BufferedStreams = "1.2.2"
CSV = "0.10.15"
DataStructures = "0.19.3"
Dates = "1.11.0"
Graphs = "1.13.4"
HTTP = "1.10.19"
JSON = "1.3.0"
LinearAlgebra = "1.12.0"
Logging = "1.11.0"
Mmap = "1.11.0"
Plots = "1.41.3"
ProfileView = "1.10.2"
Random = "1.11.0"
StaticArrays = "1.9.15"
Statistics = "1.11.1"
StatsBase = "0.34.9"
julia = "1.12"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
